=== dev-ameer-hamza/eqdaw03/fase3/lenguaje de marcas/dtd/jornadas.dtd
<!ELEMENT partidos (partido+)>
<!ELEMENT partido (ID_JORNADA, EQUIPO_1, EQUIPO_2, EQUIPO_GANADOR)>
<!ELEMENT ID_JORNADA (#PCDATA)>
<!ELEMENT EQUIPO_1 (#PCDATA)>
<!ELEMENT EQUIPO_2 (#PCDATA)>
<!ELEMENT EQUIPO_GANADOR (#PCDATA)>

=== dev-ameer-hamza/eqdaw03/LMSG/dtd/ultima_jornada_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partidos SYSTEM "jornadas.dtd">
<partidos>
 <partido>
  <ID_JORNADA>5</ID_JORNADA>
  <EQUIPO_1>equipo1</EQUIPO_1>
  <EQUIPO_2>equipo4</EQUIPO_2>
  <EQUIPO_GANADOR>equipo1</EQUIPO_GANADOR>
 </partido>
 <partido>
  <ID_JORNADA>5</ID_JORNADA>
  <EQUIPO_1>equipo2</EQUIPO_1>
  <EQUIPO_2>equipo6</EQUIPO_2>
  <EQUIPO_GANADOR>equipo2</EQUIPO_GANADOR>
 </partido>
 <partido>
  <ID_JORNADA>5</ID_JORNADA>
  <EQUIPO_1>equipo4</EQUIPO_1>
  <EQUIPO_2>equipo5</EQUIPO_2>
  <EQUIPO_GANADOR>equipo4</EQUIPO_GANADOR>
 </partido>
</partidos>
