=== dev-ameer-hamza/eqdaw03/fase3/lenguaje de marcas/xsd/clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
          <xs:element name="clasificacion" type="tClasificacion"/>
           <xs:complexType name="tClasificacion">
                    <xs:sequence>
                            <xs:element name="equipo" type="tEquipo" maxOccurs="unbounded"/> 
                    </xs:sequence>
            </xs:complexType>

          <xs:complexType name="tEquipo">
                    <xs:sequence>
                            <xs:element name="ID_EQUIPO" type="xs:int"/> 
                            <xs:element name="NOMBRE_EQUIPO" type="xs:string"/> 
                            <xs:element name="PUNTOS" type="xs:int"/>
                            <xs:element name="PARTIDOS_JUGADOS" type="xs:int"/> 
                            <xs:element name="PARTIDOS_GANADOS" type="xs:int"/> 
                            <xs:element name="PARTIDOS_PERDIDOS" type="xs:int"/> 
                    </xs:sequence>
          </xs:complexType>
</xs:schema>

=== dev-ameer-hamza/eqdaw03/fase3/lenguaje de marcas/xsd/clasificacion_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<clasificacion xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="clasificacion.xsd">
 <equipo>
  <ID_EQUIPO>2</ID_EQUIPO>
  <NOMBRE_EQUIPO>equipo2</NOMBRE_EQUIPO>
  <PUNTOS>40</PUNTOS>
  <PARTIDOS_JUGADOS>5</PARTIDOS_JUGADOS>
  <PARTIDOS_GANADOS>2</PARTIDOS_GANADOS>
  <PARTIDOS_PERDIDOS>3</PARTIDOS_PERDIDOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>1</ID_EQUIPO>
  <NOMBRE_EQUIPO>equipo1</NOMBRE_EQUIPO>
  <PUNTOS>18</PUNTOS>
  <PARTIDOS_JUGADOS>5</PARTIDOS_JUGADOS>
  <PARTIDOS_GANADOS>3</PARTIDOS_GANADOS>
  <PARTIDOS_PERDIDOS>2</PARTIDOS_PERDIDOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>3</ID_EQUIPO>
  <NOMBRE_EQUIPO>equipo3</NOMBRE_EQUIPO>
  <PUNTOS>12</PUNTOS>
  <PARTIDOS_JUGADOS>5</PARTIDOS_JUGADOS>
  <PARTIDOS_GANADOS>1</PARTIDOS_GANADOS>
  <PARTIDOS_PERDIDOS>4</PARTIDOS_PERDIDOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>5</ID_EQUIPO>
  <NOMBRE_EQUIPO>equipo5</NOMBRE_EQUIPO>
  <PUNTOS>8</PUNTOS>
  <PARTIDOS_JUGADOS>5</PARTIDOS_JUGADOS>
  <PARTIDOS_GANADOS>4</PARTIDOS_GANADOS>
  <PARTIDOS_PERDIDOS>1</PARTIDOS_PERDIDOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>6</ID_EQUIPO>
  <NOMBRE_EQUIPO>equipo6</NOMBRE_EQUIPO>
  <PUNTOS>8</PUNTOS>
  <PARTIDOS_JUGADOS>5</PARTIDOS_JUGADOS>
  <PARTIDOS_GANADOS>4</PARTIDOS_GANADOS>
  <PARTIDOS_PERDIDOS>1</PARTIDOS_PERDIDOS>
 </equipo>
 <equipo>
  <ID_EQUIPO>4</ID_EQUIPO>
  <NOMBRE_EQUIPO>equipo4</NOMBRE_EQUIPO>
  <PUNTOS>5</PUNTOS>
  <PARTIDOS_JUGADOS>5</PARTIDOS_JUGADOS>
  <PARTIDOS_GANADOS>5</PARTIDOS_GANADOS>
  <PARTIDOS_PERDIDOS>0</PARTIDOS_PERDIDOS>
 </equipo>
</clasificacion>
